### ISSUE TITLE
Providing complex example for nested arrays

### ISSUE THREAD

**Issue by mklueh** [aldeed/autoform-demo#13]
Hi aldeed,

I really like autoform, but I'm struggling with more complex schemas as there are no clear examples.

In my case, I'm having a document containing an array within an array and I'm displaying everything on one edit page.

The functionalities I need are

1. Inserting new items into the first array
2. Updating/Removing first-level items
3. Inserting items into the array of the first-level items
4. Updating/Removing second-level items

Every item has its own sub scheme.

There is an example for updating a first-level item with the dot notation, but I haven't got that working for the inner array.

As a temporary solution I've moved the array items to a separate collection and made the saving/updating stuff by my own, but nevertheless it would be nice to see how that works out by just using autoform.

**Comment by aldeed** [comment]
This is no longer maintained.
